name: Update Pages
on: [push]
jobs:
  pages:
    permissions:
      pages: 'write'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Install dependencies
      run: npm install
    - name: Run build script
      run: npm run build
    - name: Tar files
      run: tar -cvf artifact.tar dist
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: github-pages
        path: artifact.tar
    - name: Check out deploy action
      uses: actions/checkout@v3
      with:
        repository: actions/deploy-pages
        ref: v1.0.6
        path: ./.github/actions/deploy-pages
    - name: Deploy Pages
      uses: ./.github/actions/deploy-pages