name: Update Pages
on: [push]
jobs:
  pages:
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Install dependencies
      run: npm install
    - name: Run build script
      run: npm run build
    - name: Tar files
      run: tar --dereference --hard-dereference -cvf artifact.tar dist
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: github-pages
        path: artifact.tar
    - name: Deploy Pages
      uses: actions/deploy-pages@v1-beta